name: Publish Docker Image

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  publish_docker_image:
    name: publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - id: debian
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.debian.outputs.digest }}
          push-to-registry: true

      - id: alpine
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-alpine
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.alpine.outputs.digest }}
          push-to-registry: true

